module.exports = [
    {
        languageOptions: {
            ecmaVersion: 2020,
            sourceType: "script",
            globals: {
                window: "readonly",
                document: "readonly",
                jQuery: "readonly",
                $: "readonly",
                Inputmask: "readonly",
                console: "readonly",
                setTimeout: "readonly",
                XMLHttpRequest: "readonly"
            }
        },
        rules: {
            "comma-dangle": ["error", "never"],
            "no-cond-assign": "error",
            "no-constant-condition": "error",
            "no-control-regex": "error",
            "no-debugger": "error",
            "no-dupe-args": "error",
            "no-dupe-keys": "error",
            "no-duplicate-case": "error",
            "no-empty": "error",
            "no-empty-character-class": "error",
            "no-ex-assign": "error",
            "no-extra-boolean-cast": "error",
            "no-extra-semi": "error",
            "no-func-assign": "error",
            "no-inner-declarations": ["error", "functions"],
            "no-invalid-regexp": "error",
            "no-irregular-whitespace": "error",
            "no-unsafe-negation": "error",
            "no-obj-calls": "error",
            "no-regex-spaces": "error",
            "no-sparse-arrays": "error",
            "no-unexpected-multiline": "error",
            "no-unreachable": "error",
            "use-isnan": "error",
            "valid-typeof": "error",
            "accessor-pairs": "error",
            complexity: ["warn", 6],
            eqeqeq: "warn",
            "guard-for-in": "error",
            "no-alert": "warn",
            "no-caller": "error",
            "no-case-declarations": "error",
            "no-div-regex": "error",
            "no-labels": "error",
            "no-empty-pattern": "error",
            "no-eq-null": "warn",
            "no-eval": "error",
            "no-extend-native": "error",
            "no-extra-bind": "error",
            "no-fallthrough": "error",
            "no-implied-eval": "error",
            "no-iterator": "error",
            "no-lone-blocks": "error",
            "no-loop-func": "warn",
            "no-multi-str": "error",
            "no-global-assign": "error",
            "no-new-func": "error",
            "no-new-wrappers": "warn",
            "no-new": "error",
            "no-octal-escape": "error",
            "no-octal": "error",
            "no-proto": "error",
            "no-redeclare": "error",
            "no-return-assign": "error",
            "no-script-url": "error",
            "no-self-compare": "error",
            "no-unused-expressions": "warn",
            "no-useless-call": "error",
            "no-useless-concat": "error",
            "no-void": "error",
            "no-with": "error",
            radix: "error",
            "wrap-iife": "warn",
            "no-shadow": "error",
            "no-delete-var": "error",
            "no-label-var": "error",
            "no-shadow-restricted-names": "error",
            "no-undef-init": "warn",
            "max-statements": ["warn", 30]
        }
    }
];
